[package]
name = "test-common"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.8"
axum = { version = "0.6", default-features = false }
hyper = "0.14"
serde = "1.0"
serde_json = "1.0"
tower = { version = "0.4", default-features = false }
