[package]
name = "test-common"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.6", default-features = false }
once_cell = "1.16"
hyper = "0.14"
serde_json = "1.0"
tower = { version = "0.4", default-features = false }
