#[rustfmt::skip]
pub const TEST_WILDNAMES: [(&str, Result<&[&str], ()>); 39] = [
    ("/first1", Ok(&["/*","/**"])),
    ("/first1*", Err(())),
    ("/first1**", Err(())),
    ("/first1/", Ok(&["/first1/*","/first1/**","/**"])),
    ("/first1/*", Ok(&[])),
    ("/first1/ *", Err(())),
    ("/first1/**", Ok(&[])),
    ("/first1/ **", Err(())),
    ("/first1/second2", Ok(&["/first1/*","/first1/**","/**"])),
    ("/first1/second2*", Err(())),
    ("/first1/second2**", Err(())),
    ("/first1/second2/", Ok(&["/first1/second2/*","/first1/second2/**","/first1/**","/**"])),
    ("/first1/second2/*", Ok(&[])),
    ("/first1/second2/ *", Err(())),
    ("/first1/second2/**", Ok(&[])),
    ("/first1/second2/ **", Err(())),
    ("/first1/second2/third3", Ok(&["/first1/second2/*","/first1/second2/**","/first1/**","/**"])),
    ("/first1/second2/third3*", Err(())),
    ("/first1/second2/third3**", Err(())),
    ("/first1/second2/third3/", Ok(&["/first1/second2/third3/*","/first1/second2/third3/**","/first1/second2/**","/first1/**","/**"])),
    ("/first1/second2/third3/*", Ok(&[])),
    ("/first1/second2/third3/ *", Err(())),
    ("/first1/second2/third3/**", Ok(&[])),
    ("/first1/second2/third3/ **", Err(())),
    ("/first1/second2/third3/-_!~()$@", Ok(&["/first1/second2/third3/*","/first1/second2/third3/**","/first1/second2/**","/first1/**","/**"])),
    ("/first1/second2/third3/-_!~()$@*", Err(())),
    ("/first1/second2/third3/-_!~()$@**", Err(())),
    ("/first1/second2/third3/-_!~()$@/", Ok(&["/first1/second2/third3/-_!~()$@/*","/first1/second2/third3/-_!~()$@/**","/first1/second2/third3/**","/first1/second2/**","/first1/**","/**"])),
    ("/first1/second2/third3/-_!~()$@/*", Ok(&[])),
    ("/first1/second2/third3/-_!~()$@/ *", Err(())),
    ("/first1/second2/third3/-_!~()$@/**", Ok(&[])),
    ("/first1/second2/third3/-_!~()$@/ **", Err(())),
    ("/first1/*/third3", Err(())),
    ("/first1/*/third3/", Err(())),
    ("/first1/*/third3/*", Err(())),
    ("/first1/*/third3/**", Err(())),
    ("/first1/second2/**/", Err(())),
    ("/first1/second2/**/*", Err(())),
    ("/first1/second2/**/**", Err(())),
];
