[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum-cometd = { path = "../../" }
axum = { version = "0.5.17", default-features = false }
tokio = { version = "1.22.0", features = ["macros", "rt-multi-thread", "time"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
serde = { version = "1.0.147", features = ["derive"] }
